import React, { useState, useEffect } from 'react';
import { Target, Info, HelpCircle, Rocket, Layers, Server, Check, X } from 'lucide-react';

const AVAILABLE_COOKBOOKS = [
  { id: 'nginx', label: 'nginx', recipe: 'recipe[nginx::default]', desc: 'Nginx reverse proxy, TLS certificates & gzip' },
  { id: 'app_server', label: 'app_server', recipe: 'recipe[app_server::default]', desc: 'FastAPI / Python app cluster & systemd service' },
  { id: 'postgresql', label: 'postgresql', recipe: 'recipe[postgresql::default]', desc: 'PostgreSQL 15 relational database & tuning' },
  { id: 'monitoring', label: 'monitoring', recipe: 'recipe[monitoring::default]', desc: 'Prometheus Node Exporter & telemetry agents' }
];

const AVAILABLE_SALT_STATES = [
  { id: 'common', label: 'common', state: 'common', desc: 'Base packages, SSH authorized_keys & sysctl hardening' },
  { id: 'nginx', label: 'nginx', state: 'nginx', desc: 'Nginx vhost configs & zero-downtime reloads' },
  { id: 'app_server', label: 'app_server', state: 'app_server', desc: 'Python virtualenv, gunicorn/uvicorn processes' },
  { id: 'postgresql', label: 'postgresql', state: 'postgresql', desc: 'Postgres clusters, roles, permissions & databases' },
  { id: 'monitoring', label: 'monitoring', state: 'monitoring', desc: 'Prometheus scrapers, Grafana agent endpoints' },
  { id: 'highstate', label: 'state.highstate', state: 'highstate', desc: 'Declarative full cluster synchronization' }
];

const TARGET_PRESETS = [
  { label: 'All Fleet (*)', value: '*', desc: 'Orchestrate across every managed server' },
  { label: 'Web Tier (web-*)', value: 'web-*', desc: 'Only reverse proxies and load balancers' },
  { label: 'App Cluster (app-*)', value: 'app-*', desc: 'Only FastAPI / backend microservice nodes' },
  { label: 'Database (db-*)', value: 'db-*', desc: 'Only primary & replica database instances' },
  { label: 'Monitoring (mon-*)', value: 'mon-*', desc: 'Only Prometheus & telemetry agents' }
];

export function DeploymentModal({ isOpen, onClose, onSubmit, servers = [], initialPlan = null }) {
  if (!isOpen) return null;

  // Selected multi-select states
  const [selectedCookbooks, setSelectedCookbooks] = useState(['nginx', 'app_server']);
  const [selectedSaltStates, setSelectedSaltStates] = useState(['common', 'postgresql', 'monitoring']);
  const [showTargetTutorial, setShowTargetTutorial] = useState(false);

  const [formData, setFormData] = useState({
    name: 'Deploy Stack Update',
    description: '',
    environment: 'production',
    tool: 'both',
    target_hosts: '*',
    dry_run: false
  });

  const [loading, setLoading] = useState(false);

  // Pre-fill modal if initialPlan was generated by Nova Copilot
  useEffect(() => {
    if (initialPlan) {
      const toolEngine = initialPlan.tool || (initialPlan.engine === 'hybrid' ? 'both' : (initialPlan.engine || 'both'));
      setFormData(prev => ({
        ...prev,
        name: initialPlan.name || initialPlan.deployment_name || 'Deploy Stack Update',
        description: initialPlan.description || '',
        environment: (initialPlan.environment || 'production').toLowerCase(),
        tool: toolEngine,
        target_hosts: initialPlan.target_hosts || initialPlan.targets || '*',
        dry_run: !!initialPlan.dry_run
      }));

      if (initialPlan.chef_runlist) {
        const cbs = initialPlan.chef_runlist.split(',').map(s => {
          const match = s.match(/recipe\[([a-zA-Z0-9_-]+)/);
          return match ? match[1] : s.trim();
        }).filter(Boolean);
        if (cbs.length > 0) setSelectedCookbooks(cbs);
      }

      if (initialPlan.salt_states) {
        const sts = initialPlan.salt_states.split(',').map(s => s.trim()).filter(Boolean);
        if (sts.length > 0) setSelectedSaltStates(sts);
      }
    }
  }, [initialPlan]);

  // ── Keyboard Listener (Close on ESC) ────────────────────────
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  // Toggle Chef Cookbook
  const toggleCookbook = (id) => {
    setSelectedCookbooks(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  };

  // Toggle Salt State
  const toggleSaltState = (id) => {
    setSelectedSaltStates(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  };

  // Select all or clear
  const selectAllCookbooks = () => setSelectedCookbooks(AVAILABLE_COOKBOOKS.map(c => c.id));
  const clearCookbooks = () => setSelectedCookbooks([]);
  const selectAllSaltStates = () => setSelectedSaltStates(AVAILABLE_SALT_STATES.map(s => s.id));
  const clearSaltStates = () => setSelectedSaltStates([]);

  // Toggle individual server from list
  const toggleServerTarget = (hostname) => {
    const current = formData.target_hosts.trim();
    if (current === '*' || !current) {
      setFormData({ ...formData, target_hosts: hostname });
      return;
    }
    const hosts = current.split(',').map(h => h.trim()).filter(Boolean);
    if (hosts.includes(hostname)) {
      const remaining = hosts.filter(h => h !== hostname);
      setFormData({ ...formData, target_hosts: remaining.length > 0 ? remaining.join(', ') : '*' });
    } else {
      setFormData({ ...formData, target_hosts: [...hosts, hostname].join(', ') });
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    // Build runlist & states from multi-select
    const chef_runlist = selectedCookbooks
      .map(id => AVAILABLE_COOKBOOKS.find(c => c.id === id)?.recipe)
      .filter(Boolean)
      .join(', ');

    const salt_states = selectedSaltStates
      .map(id => AVAILABLE_SALT_STATES.find(s => s.id === id)?.state)
      .filter(Boolean)
      .join(', ');

    await onSubmit({
      ...formData,
      chef_runlist: (formData.tool === 'chef' || formData.tool === 'both') ? chef_runlist : null,
      salt_states: (formData.tool === 'salt' || formData.tool === 'both') ? salt_states : null
    });

    setLoading(false);
    onClose();
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fade-in overflow-y-auto cursor-pointer"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        className="card-cyber-elevated relative w-full max-w-2xl my-8 rounded-2xl p-6 overflow-hidden border border-white/[0.1] shadow-2xl cursor-default"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Ambient background glow */}
        <div className="absolute top-0 right-0 w-80 h-80 bg-gradient-to-br from-cyan-500/10 via-orange-500/10 to-transparent rounded-full blur-3xl pointer-events-none -mr-20 -mt-20" />

        <div className="flex items-center justify-between pb-4 border-b border-white/[0.08] relative z-10">
          <div>
            <h3 className="text-base font-extrabold text-white tracking-wide">Create New Deployment</h3>
            <p className="text-xs text-slate-400 mt-0.5">Orchestrate infrastructure with Chef & SaltStack</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-xl flex items-center justify-center text-slate-400 hover:text-white hover:bg-white/[0.08] transition text-base cursor-pointer"
            title="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="mt-5 space-y-4 relative z-10 max-h-[75vh] overflow-y-auto pr-1">
          {/* Deployment Name */}
          <div>
            <label className="block text-xs font-bold text-slate-300 mb-1.5">Deployment Name</label>
            <input
              type="text"
              required
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full bg-[#070b14] border border-white/[0.1] rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400/50 transition font-medium"
            />
          </div>

          {/* Environment & Tool Engine */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            <div>
              <label className="block text-xs font-bold text-slate-300 mb-1.5">Target Environment</label>
              <select
                value={formData.environment}
                onChange={(e) => setFormData({ ...formData, environment: e.target.value })}
                className="w-full bg-[#070b14] border border-white/[0.1] rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-cyan-400 transition"
              >
                <option value="production">Production</option>
                <option value="staging">Staging</option>
                <option value="development">Development</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-300 mb-1.5">Tooling Engine</label>
              <select
                value={formData.tool}
                onChange={(e) => setFormData({ ...formData, tool: e.target.value })}
                className="w-full bg-[#070b14] border border-white/[0.1] rounded-xl px-3.5 py-2 text-xs text-white focus:outline-none focus:border-cyan-400 transition"
              >
                <option value="both">Hybrid (Chef + SaltStack)</option>
                <option value="chef">Chef Only (Ruby Cookbooks)</option>
                <option value="salt">SaltStack Only (YAML States)</option>
              </select>
            </div>
          </div>

          {/* ──────────────────────────────────────────────────────────
              TARGET HOSTS & MINIONS TUTORIAL & MULTI-SELECT PICKER
             ────────────────────────────────────────────────────────── */}
          <div className="p-4 rounded-xl bg-[#070b14]/90 border border-white/[0.08] space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold text-slate-200 flex items-center gap-1.5">
                <Target className="w-3.5 h-3.5 text-cyan-400" />
                <span>Target Hosts / Minions</span>
                <span className="text-[10px] text-slate-500 font-normal">(Who receives this rollout)</span>
              </label>

              {/* Tutorial toggle button */}
              <button
                type="button"
                onClick={() => setShowTargetTutorial(!showTargetTutorial)}
                className="text-[11px] font-semibold text-cyan-400 hover:text-cyan-300 flex items-center gap-1 transition"
              >
                <HelpCircle className="w-3 h-3 text-cyan-400" />
                <span>{showTargetTutorial ? 'Hide Guide' : 'What is a Host / Minion?'}</span>
              </button>
            </div>

            {/* Educational Tutorial Card */}
            {showTargetTutorial && (
              <div className="p-3.5 rounded-xl bg-cyan-500/[0.07] border border-cyan-500/20 text-xs text-slate-300 space-y-2 animate-fade-in leading-relaxed">
                <div className="font-bold text-cyan-300 flex items-center gap-1.5">
                  <Info className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Target Hosts vs. Minions Guide</span>
                </div>
                <p>
                  • In <strong>Chef</strong>, servers being managed are called <strong>Nodes</strong> (e.g. <code className="text-orange-300 bg-black/40 px-1 py-0.5 rounded">prod-web-01</code>). They run the Chef Client.
                </p>
                <p>
                  • In <strong>SaltStack</strong>, servers running the Salt agent are called <strong>Minions</strong> (e.g. <code className="text-cyan-300 bg-black/40 px-1 py-0.5 rounded">minion-prod-app-01</code>).
                </p>
                <p>
                  • <strong>Targeting Rules:</strong>
                  <br />- <code className="text-white font-mono bg-black/50 px-1.5 py-0.2 rounded">*</code> = Deploys to <strong>EVERY node</strong> in the cluster.
                  <br />- <code className="text-white font-mono bg-black/50 px-1.5 py-0.2 rounded">web-*</code> = Matches only web reverse proxies.
                  <br />- <code className="text-white font-mono bg-black/50 px-1.5 py-0.2 rounded">prod-app-01, prod-db-01</code> = Targets specific comma-separated nodes.
                </p>
              </div>
            )}

            {/* Quick Target Presets */}
            <div>
              <span className="block text-[11px] font-semibold text-slate-400 mb-1.5">Quick Targeting Presets:</span>
              <div className="flex flex-wrap gap-1.5">
                {TARGET_PRESETS.map((p) => {
                  const isSelected = formData.target_hosts === p.value;
                  return (
                    <button
                      key={p.value}
                      type="button"
                      onClick={() => setFormData({ ...formData, target_hosts: p.value })}
                      className={`text-[11px] font-semibold px-2.5 py-1 rounded-lg border transition ${
                        isSelected
                          ? 'bg-cyan-500/25 border-cyan-400 text-cyan-200 shadow-[0_0_10px_rgba(6,182,212,0.2)]'
                          : 'bg-white/[0.04] border-white/[0.08] text-slate-400 hover:text-slate-200 hover:border-white/20'
                      }`}
                      title={p.desc}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Interactive Server Checkbox Chips */}
            {servers && servers.length > 0 && (
              <div>
                <span className="block text-[11px] font-semibold text-slate-400 mb-1.5">Or Pick Specific Cluster Nodes:</span>
                <div className="flex flex-wrap gap-1.5">
                  {servers.map((srv) => {
                    const isChecked = formData.target_hosts.includes(srv.hostname);
                    return (
                      <button
                        key={srv.id}
                        type="button"
                        onClick={() => toggleServerTarget(srv.hostname)}
                        className={`text-[11px] font-mono px-2.5 py-1 rounded-lg border flex items-center gap-1.5 transition ${
                          isChecked
                            ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-300 font-bold'
                            : 'bg-white/[0.03] border-white/[0.06] text-slate-400 hover:text-slate-200'
                        }`}
                      >
                        <span>{isChecked ? <Check className="w-3 h-3 text-emerald-300" /> : '+'}</span>
                        <span>{srv.hostname}</span>
                        <span className="text-[9px] uppercase px-1 py-0.2 rounded bg-black/40 text-slate-500">{srv.role}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Custom Target Hosts Text Input */}
            <div>
              <input
                type="text"
                value={formData.target_hosts}
                onChange={(e) => setFormData({ ...formData, target_hosts: e.target.value })}
                placeholder="e.g. * or web-*, db-01"
                className="w-full bg-[#05070d] border border-white/[0.1] rounded-xl px-3.5 py-2 text-xs text-white font-mono focus:outline-none focus:border-cyan-400 transition"
              />
            </div>
          </div>

          {/* ──────────────────────────────────────────────────────────
              1. CHEF COOKBOOKS MULTI-SELECT CHIPS
             ────────────────────────────────────────────────────────── */}
          {(formData.tool === 'chef' || formData.tool === 'both') && (
            <div className="p-4 rounded-xl bg-orange-500/[0.04] border border-orange-500/25 space-y-2.5">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-xs font-bold text-orange-400 flex items-center gap-1.5">
                    <Layers className="w-3.5 h-3.5 text-orange-400" />
                    <span>Chef Cookbooks & Runlist</span>
                    <span className="text-[10px] text-orange-300/80 font-normal">
                      ({selectedCookbooks.length} selected)
                    </span>
                  </label>
                  <p className="text-[11px] text-slate-400">Select multiple Ruby cookbooks to converge</p>
                </div>
                <div className="flex items-center gap-2 text-[10px]">
                  <button
                    type="button"
                    onClick={selectAllCookbooks}
                    className="text-orange-400 hover:underline font-semibold"
                  >
                    Select All
                  </button>
                  <span className="text-slate-600">|</span>
                  <button
                    type="button"
                    onClick={clearCookbooks}
                    className="text-slate-500 hover:text-slate-300 font-semibold"
                  >
                    Clear
                  </button>
                </div>
              </div>

              {/* Multi-Select Pills */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {AVAILABLE_COOKBOOKS.map((cb) => {
                  const isChecked = selectedCookbooks.includes(cb.id);
                  return (
                    <div
                      key={cb.id}
                      onClick={() => toggleCookbook(cb.id)}
                      className={`p-2.5 rounded-xl border cursor-pointer transition select-none flex items-start gap-2.5 ${
                        isChecked
                          ? 'bg-orange-500/15 border-orange-500/40 shadow-[0_0_12px_rgba(249,115,22,0.15)]'
                          : 'bg-[#070b14]/70 border-white/[0.06] hover:border-orange-500/20'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => {}}
                        className="mt-0.5 rounded bg-[#070b14] border-orange-500/40 text-orange-500 focus:ring-0"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <span className={`text-xs font-mono font-bold ${isChecked ? 'text-orange-300' : 'text-slate-300'}`}>
                            {cb.label}
                          </span>
                          <span className="text-[10px] text-orange-400/70 font-mono">1.0.0</span>
                        </div>
                        <p className="text-[10px] text-slate-400 mt-0.5 leading-snug truncate">{cb.desc}</p>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Resolved Chef Runlist Preview */}
              <div className="text-[10px] font-mono text-slate-500 bg-[#05070d] p-2 rounded-lg border border-orange-500/15">
                <span className="text-orange-400 font-bold">Runlist: </span>
                {selectedCookbooks.length > 0
                  ? selectedCookbooks.map(id => `recipe[${id}::default]`).join(', ')
                  : '<None selected>'}
              </div>
            </div>
          )}

          {/* ──────────────────────────────────────────────────────────
              2. SALTSTACK STATES MULTI-SELECT CHIPS
             ────────────────────────────────────────────────────────── */}
          {(formData.tool === 'salt' || formData.tool === 'both') && (
            <div className="p-4 rounded-xl bg-cyan-500/[0.04] border border-cyan-500/25 space-y-2.5">
              <div className="flex items-center justify-between">
                <div>
                  <label className="text-xs font-bold text-cyan-400 flex items-center gap-1.5">
                    <Server className="w-3.5 h-3.5 text-cyan-400" />
                    <span>SaltStack States (SLS Formulas)</span>
                    <span className="text-[10px] text-cyan-300/80 font-normal">
                      ({selectedSaltStates.length} selected)
                    </span>
                  </label>
                  <p className="text-[11px] text-slate-400">Select multiple declarative YAML states to apply</p>
                </div>
                <div className="flex items-center gap-2 text-[10px]">
                  <button
                    type="button"
                    onClick={selectAllSaltStates}
                    className="text-cyan-400 hover:underline font-semibold"
                  >
                    Select All
                  </button>
                  <span className="text-slate-600">|</span>
                  <button
                    type="button"
                    onClick={clearSaltStates}
                    className="text-slate-500 hover:text-slate-300 font-semibold"
                  >
                    Clear
                  </button>
                </div>
              </div>

              {/* Multi-Select Pills */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {AVAILABLE_SALT_STATES.map((st) => {
                  const isChecked = selectedSaltStates.includes(st.id);
                  return (
                    <div
                      key={st.id}
                      onClick={() => toggleSaltState(st.id)}
                      className={`p-2.5 rounded-xl border cursor-pointer transition select-none flex items-start gap-2.5 ${
                        isChecked
                          ? 'bg-cyan-500/15 border-cyan-500/40 shadow-[0_0_12px_rgba(6,182,212,0.15)]'
                          : 'bg-[#070b14]/70 border-white/[0.06] hover:border-cyan-500/20'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => {}}
                        className="mt-0.5 rounded bg-[#070b14] border-cyan-500/40 text-cyan-500 focus:ring-0"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between">
                          <span className={`text-xs font-mono font-bold ${isChecked ? 'text-cyan-300' : 'text-slate-300'}`}>
                            {st.label}
                          </span>
                          <span className="text-[10px] text-cyan-400/70 font-mono">.sls</span>
                        </div>
                        <p className="text-[10px] text-slate-400 mt-0.5 leading-snug truncate">{st.desc}</p>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Resolved Salt States Preview */}
              <div className="text-[10px] font-mono text-slate-500 bg-[#05070d] p-2 rounded-lg border border-cyan-500/15">
                <span className="text-cyan-400 font-bold">States: </span>
                {selectedSaltStates.length > 0
                  ? selectedSaltStates.join(', ')
                  : '<None selected>'}
              </div>
            </div>
          )}

          {/* Dry Run Checkbox */}
          <div className="flex items-center gap-2.5 pt-1">
            <input
              type="checkbox"
              id="dry_run"
              checked={formData.dry_run}
              onChange={(e) => setFormData({ ...formData, dry_run: e.target.checked })}
              className="rounded bg-[#070b14] border-white/20 text-cyan-400 focus:ring-0 focus:ring-offset-0"
            />
            <label htmlFor="dry_run" className="text-xs text-slate-300 font-medium cursor-pointer select-none">
              Dry-run simulation mode (Chef why-run / Salt test=True)
            </label>
          </div>

          {/* Submit Actions */}
          <div className="flex items-center justify-end gap-3 pt-4 border-t border-white/[0.08]">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white hover:bg-white/[0.06] transition"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="px-5 py-2.5 rounded-xl text-xs font-extrabold text-white bg-gradient-to-r from-orange-500 via-amber-500 to-cyan-500 hover:opacity-95 shadow-[0_0_20px_rgba(249,115,22,0.3)] transition active:scale-95 disabled:opacity-50 flex items-center gap-2 cursor-pointer"
            >
              <span>{loading ? 'Queueing...' : 'Launch Deployment'}</span>
              <Rocket className="w-3.5 h-3.5" />
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
