# Salt managed postgresql.conf
listen_addresses = '{{ listen_addresses }}'
port = 5432
max_connections = {{ max_connections }}
shared_buffers = {{ shared_buffers }}
datestyle = 'iso, ymd'
timezone = 'UTC'
